package com.shubham.hiltdemo

import android.app.Application
import dagger.hilt.android.HiltAndroidApp

@HiltAndroidApp // <- this annotation triggers hilts code generation including the base class for your application that serves as the application-level dependency container.
class App: Application()  // and then we don't need to do anything else in this class. All other required codes for the application class will be auto-generated by the hilt library.

/* commented because added @HiltAndroidApp
{
    lateinit var dataComponent: DataComponent

    override fun onCreate() {
        super.onCreate()

        dataComponent = DaggerDataComponent.builder()
            .build()
    }

}*/
